/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated code. Do not edit.

using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using Google.GenAI.Serialization;

namespace Google.GenAI.Types {
  /// <summary>
  /// Success and error statistics of processing multiple entities (for example, DataItems or
  /// structured data rows) in batch. This data type is not supported in Gemini API.
  /// </summary>

  public record CompletionStats {
    /// <summary>
    /// Output only. The number of entities for which any error was encountered.
    /// </summary>
    [JsonPropertyName("failedCount")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(StringToNullableLongConverter))]
    public long ? FailedCount { get; set; }

    /// <summary>
    /// Output only. In cases when enough errors are encountered a job, pipeline, or operation may
    /// be failed as a whole. Below is the number of entities for which the processing had not been
    /// finished (either in successful or failed state). Set to -1 if the number is unknown (for
    /// example, the operation failed before the total entity number could be collected).
    /// </summary>
    [JsonPropertyName("incompleteCount")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(StringToNullableLongConverter))]
    public long
        ? IncompleteCount {
            get; set;
          }

    /// <summary>
    /// Output only. The number of entities that had been processed successfully.
    /// </summary>
    [JsonPropertyName("successfulCount")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(StringToNullableLongConverter))]
    public long
        ? SuccessfulCount {
            get; set;
          }

    /// <summary>
    /// Output only. The number of the successful forecast points that are generated by the
    /// forecasting model. This is ONLY used by the forecasting batch prediction.
    /// </summary>
    [JsonPropertyName("successfulForecastPointCount")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(StringToNullableLongConverter))]
    public long
        ? SuccessfulForecastPointCount {
            get; set;
          }

    /// <summary>
    /// Deserializes a JSON string to a CompletionStats object.
    /// </summary>
    /// <param name="jsonString">The JSON string to deserialize.</param>
    /// <param name="options">Optional JsonSerializerOptions.</param>
    /// <returns>The deserialized CompletionStats object, or null if deserialization
    /// fails.</returns>
    public static CompletionStats
        ? FromJson(string jsonString, JsonSerializerOptions? options = null) {
      try {
        return JsonSerializer.Deserialize<CompletionStats>(jsonString, options);
      } catch (JsonException e) {
        Console.Error.WriteLine($"Error deserializing JSON: {e.ToString()}");
        return null;
      }
    }
  }
}
